variables:
  TF_VAR_CI_COMMIT_REF_NAME: "$CI_COMMIT_REF_NAME"
  TF_VAR_AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
  TF_VAR_AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"
  TF_VAR_ssh_username: "$TEMPLATE_USERNAME"
  TF_VAR_ssh_private_key: "$SSH_PRIVATE_KEY"

stages:
  - validate
  - plan
  - deploy

default:
  before_script:
    - mkdir -p /root/.ssh
    - echo $SSH_PRIVATE_KEY | base64 -d > /root/.ssh/id_rsa && chmod 600 /root/.ssh/id_rsa
    - echo $SSH_PUBLIC_KEY | base64 -d > /root/.ssh/id_rsa.pub && chmod 644 /root/.ssh/id_rsa.pub

validate:
  stage: validate
  image:
    name: hashicorp/terraform:0.12.7
    entrypoint: [""]
  script:
    - ssh-keyscan gitlab.com > /root/.ssh/known_hosts && chmod 644 /root/.ssh/known_hosts
    - cd src
    - terraform init -input=false
    - terraform validate
  artifacts:
    paths:
      - src/.terraform/

.plan_template: &plan
  stage: plan
  image:
    name: hashicorp/terraform:0.12.7
    entrypoint: [""]
  script:
    - apk add bash jq
    - cd src
    - terraform workspace select $WORKSPACE || terraform workspace new $WORKSPACE
    - terraform plan -out salt-orchestration.plan
  artifacts:
    paths:
      - src/salt-orchestration.plan

development_plan:
  <<: *plan
  variables:
    WORKSPACE: "dev"
  only:
    - development

production_plan:
  <<: *plan
  variables:
    WORKSPACE: "prod"
  only:
    - production

.deploy_template: &deploy
  stage: deploy
  image:
    name: hashicorp/terraform:0.12.7
    entrypoint: [""]
  script:
    - cd src
    - terraform workspace select $WORKSPACE || terraform workspace new $WORKSPACE
    - terraform apply -auto-approve salt-orchestration.plan

development_deploy:
  <<: *deploy
  variables:
    WORKSPACE: "dev"
  only:
    - development

production_deploy:
  <<: *deploy
  variables:
    WORKSPACE: "prod"
  only:
    - production
